version: '3'

services:
  tomcat:
    build: .
    image: tomcat
    ports:
      - 9090:8080
    networks:
      - tomcat-network
    container_name: tomcat

  httpd:
    build: ./httpd
    image: httpd
    ports:
      - 8880:80
    networks:
      - tomcat-network
    container_name: httpd
    depends_on: 
      - tomcat

networks:
  tomcat-network:
