version: '3'

services:
  tomcat:
    build: .
    image: ${ECR_REPO}:tomcat_myFirstServlet 
    ports:
      - 9090:8080
    networks:
      - tomcat-network
    container_name: tomcat

  httpd:
    build: ./httpd
    image: ${ECR_REPO}:httpd_myFirstServlet
    ports:
      - 8880:80
    networks:
      - tomcat-network
    container_name: httpd
    depends_on: 
      - tomcat

networks:
  tomcat-network:
